name: Bug Report
description: File a bug/issue report
title: "[BUG]: "
labels: [ "bug" ]
assignees:
  - yogwoggf
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help us reproduce and fix the issue, ensuring that you provide as much information as possible.
  - type: input
    id: gpu
    attributes:
      label: GPU
      description: The GPU you are using to run Gelly
      placeholder: e.g. NVIDIA GeForce RTX 3090
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      description: The operating system you are using to run Gelly
      placeholder: e.g. Windows 11
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Is this specific to performance?
      description: Check this box if the issue is related to performance, but NOT if it is distinctly low FPS with no fluid spawned.
      options:
        - label: "Yes"
        - label: "No"
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: The type of issue you are experiencing
      options:
        - Crash
        - Flickering
        - Freezing
        - Low FPS
        - Other
  - type: textarea
    id: incident
    attributes:
      label: Incident Description
      description: Describe the issue you are experiencing
      placeholder: e.g. When I run Gelly, the game crashes after 5 minutes of gameplay
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Log
      description: Provide any logs or error messages you are seeing. You can find your logs in the GMod folder. They look like 'gelly-log-xxxxxx.txt'
      placeholder: Copy and paste the contents of the log file here, if applicable