name: Create Production Release
run-name: Create Production Release (x64, Windows)
on:
  push:
    branches:
      - master
jobs:
  create-release:
    runs-on: windows-latest
    steps:
      - name: Checkout latest Gelly
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          ref: master
      - name: Set up Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.0'
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64 # once this is run, gelly-production-release.zip will be created in the root of the repository, and we can just ignore the rest
      - name: Set up x64 Developer Command Prompt for VS 2022
        run: |
          python scripts/make-release.py
      - name: Upload Release
        uses: actions/upload-release-asset@v1
        if: startsWith(github.ref, 'refs/tags/v') # We still want to create a release, but not upload the asset if it's not a tagged release
        with:
          files: gelly-production-release.zip